### ISSUE TITLE
Publishing error - No Configuration or Migration File is Created

### ISSUE THREAD

**Issue by shagor424** [arif98741/laravelbdsms#43]
![Capture](https://github.com/arif98741/laravelbdsms/assets/69715572/5e200dc6-b453-4aeb-9b26-e7bd2ed42270)

new laravel new project e kaz kore . but old project e kaz kore na

**Comment by arif98741** [comment]
No issue found. Just tested. Can you mention which your laravel version and php version?
![Screenshot 2023-07-23 135146](https://github.com/arif98741/laravelbdsms/assets/17213478/3e4ece7d-82bf-4199-ae9d-bf8d8f846b04)

**Comment by shagor424** [comment]
9,8,7

**Comment by shagor424** [comment]
Laravel version factor na.. factor holo kono project e Jodi age kono package use kora thake tokhon problem hoi

**Comment by arif98741** [comment]
I have already diffrent packages in system.
<pre>
 "require": {
        "php": "^8.1",
        "dompdf/dompdf": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "spatie/laravel-permission": "^5.10",
        "tecnickcom/tcpdf": "^6.6"
    },
</pre>

After installing and publishing vendor still got no error. I think you have issues in your other composer packges, that might be conflicting with others

`php artisan vendor:publish --provider=Xenon\LaravelBDSms\LaravelBDSmsServiceProvider`
![Screenshot 2023-07-23 184603](https://github.com/arif98741/laravelbdsms/assets/17213478/749db631-dcb2-451f-abdf-0df1689ad06d)

**Comment by arif98741** [comment]
Share your project `composer.json` file here

**Comment by arif98741** [comment]
> Laravel version factor na.. factor holo kono project e Jodi age kono package use kora thake tokhon problem hoi


Share your project composer.json file here
