### ISSUE TITLE
Add ADN sms and mobile operator api

### ISSUE THREAD

**Issue by n4yeem** [arif98741/laravelbdsms#5]
Hi

Can you add adn sms and mobile operator sms api with this project. it will make this project more fruitful. Thanks

**Comment by arif98741** [comment]
> Hi
> 
> Can you add adn sms and mobile operator sms api with this project. it will make this project more fruitful. Thanks

thanks for mentioning. you will be happy to know that provider **ADN** is already added in this package. But by mistake it was not added to readme.md file. You can use adn. 
if you face any issues or errors during use **ADN** provider from this package, you can mention here. I will try to solve .

**Comment by arif98741** [comment]
> Hi
> 
> Can you add adn sms and mobile operator sms api with this project. it will make this project more fruitful. Thanks

I updated the readme.md

**Comment by arif98741** [comment]
> Hi
> 
> Can you add adn sms and mobile operator sms api with this project. it will make this project more fruitful. Thanks

I still have not got opportunity to work with mobile operator sms api. that's why I still have not added . If you have any documentation for mobile operators such as GP/BL/Robi then you can forward me. Hope that it will help you as well as other laravel developers around Bangladesh
