### ISSUE TITLE
Bulk SMS BD api mobile number and message formate not correct. 

### ISSUE THREAD

**Issue by Islamshawon71** [arif98741/laravelbdsms#6]
Update this on 

use Xenon\LaravelBDSms\Provider\BulkSmsBD;

'username' => $config['username'],
                'password' => $config['password'],
                'number' => $number,
                'message' => $text,

**Comment by arif98741** [comment]
can u share exact response please?
which version of laravelbdsms package you are using ?

**Comment by arif98741** [comment]
According to my findings and observation I think that you are using **xenon/laravelbdsms** which is lower version than **v1.0.38.***
From version **v1.0.38.*** mobile number format and length validation has been removed because sometimes it creates issue for several sms gateways. 

I suggest you to upgrade your **xenon/laravelbdsms** to **v1.0.38.*** . 
Use below command for upgrading your package

> **composer update xenon/laravelbdsms**

**Comment by Islamshawon71** [comment]
I got problem with this line : Phone number
https://github.com/arif98741/laravelbdsms/blob/2f14e733fd43e3e4cf0dba3b0c2d347c07b73d9a/src/Provider/BulkSmsBD.php#L49

$response = $client->request('GET', '', [
            'query' => [
                'username' => $config['username'],
                'password' => $config['password'],
                'contacts' => $number,
                'msg' => $text,
            ]
        ]);
        
![image](https://user-images.githubusercontent.com/7997828/155010722-23748262-2d00-460d-b544-07bc544ba5ce.png)

![image](https://user-images.githubusercontent.com/7997828/155010804-b29d2308-9ae3-4b5c-b74c-97bd758c673b.png)

not are same as document. thats why didn't get response properly.

**Comment by Islamshawon71** [comment]
<img width="1048" alt="Screenshot 2022-02-22 at 12 40 32 AM" src="https://user-images.githubusercontent.com/7997828/155011178-e8834452-b9c2-4804-96c2-0b04f21da841.png">

**Comment by arif98741** [comment]
> 

Thanks for your great contribution to find out this bug. I am updating this query param by _number_ soon and pushing a new release. Please update your package.

**Comment by arif98741** [comment]
New version _v1.0.38.2_ is released after fixing that bug. 

@Islamshawon71 
Special thanks for your nice contribution. Hope you will continue to participate in open source world in future also. 
I am closing this issue soon. If you need to mention something new you can reopen it.
