### ISSUE TITLE
SQLSTATE[HY000] [1040] Too many connections

### ISSUE THREAD

**Issue by irabbi360** [arif98741/laravelbdsms#70]
![image](https://github.com/arif98741/laravelbdsms/assets/35403788/ff951457-b122-47ed-afcd-1c0f15dbf50d)

**Comment by arif98741** [comment]
can you update your xenon/laravelbdsms to **V1.0.57.2** now ?

**Comment by irabbi360** [comment]
Issues solved. Thank you.
